### ISSUE TITLE
Upload format

### ISSUE THREAD

**Issue by sam-suresh** [lushonline/moodle-tool_uploadpage#9]
Can you provide a sample CSV file? 

For example, COURSE_VISIBLE should be `1` or `SHOW`

Also, I'm getting this error `File format is invalid. Parent category is invalid.`
As far as I see there are category id and category only. Whats is this about the parent category? 

Thank you for contributing this plugin and your time

**Comment by lushonline** [comment]
Sam the columns and example information is documented here:
https://github.com/lushonline/moodle-tool_uploadpage/wiki/Format-of-Import-File

I assume you are using the CLI, in which case you need to get the "parent category" ID from in your Moodle site. This is the value of a category. Again see:
https://github.com/lushonline/moodle-tool_uploadpage/wiki/Running-from-Command-Line

If you upload in the Moodle UI you get a "drop down" to select the Parent

You can also find example CSV files, in https://github.com/lushonline/moodle-tool_uploadpage/tree/master/tests/fixtures

**Comment by sam-suresh** [comment]
Thank you

**Comment by sam-suresh** [comment]
>If you upload in the Moodle UI you get a "drop down" to select the Parent

Actually there is no parent category option in the UI. I thinks its missing? 
Therefore, we cannot upload using the UI.

<img width="1135" alt="Screenshot 2020-08-11 at 8 14 34 AM" src="https://user-images.githubusercontent.com/5198092/89843272-b670f200-dbaa-11ea-9994-a4a85c27ae06.png">
<img width="817" alt="Screenshot 2020-08-11 at 8 14 27 AM" src="https://user-images.githubusercontent.com/5198092/89843276-bbce3c80-dbaa-11ea-966a-9c929fb98480.png">

**Comment by lushonline** [comment]
Sam
Can you send details of the version of Moodle you are using, best to share the full contents of the version.php file

Plus confirm that you have at least the default categories configured in Moodle.

Also can you try using the CORE "Import Courses" option (you will need to create a file for this its not the same as mine) and see if that works. My import is based very closely on logic for the CORE import courses and I want to see if this fails in your site as well.

Also share a copy of your file

**Comment by lushonline** [comment]
I think I may have identified the issue, leave it with me
